version: '3'
services:
  stones_ui:
    container_name: "stones_ui"
    image: stones_ui
    ports:
      - "80:80"
    build:
      context: ./stones_ui
    depends_on:
      - postgres
      - stones_web
    networks:
      - custom

  stones_web:
    container_name: "stones_web"
    image: stones_web
    ports:
      - "8000:8000"
    volumes:
      - ./stones_web:/opt/app
    command: python start.py
    env_file:
      - .env
    build:
      context: ./stones_web
    depends_on:
      - postgres
    networks:
      - custom

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=brick
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=stone
    ports:
      - "5432:5432"
    restart: always
    networks:
      - custom

networks:
    custom:
      driver: bridge